In [1]:
import pandas as pd

In [2]:
# creating the dataframe 

df = pd.read_csv(r'D:\Documents\Operation UPSKILL\Side Projects\Datasets\terrorist-attacks.csv')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

df.head()

,Entity,Code,Year,Terrorist attacks,Terrorism deaths,Attack method: Hijacking,Attack method: Hostage Taking (Barricade Incident),Attack method: Unarmed Assault,Attack method: Facility/Infrastructure Attack,Attack method: Hostage Taking (Kidnapping),Attack method: Assassination,Attack method: Armed Assault,Attack method: Bombing/Explosion,Death Age 100+,Death Age: 51-99,Death Age : 21-50,Death Age : 11-20,Death Age : 6-10,Death Age : 1-5,Terrorist Death Type : Suicide,Terrorist Death Type : Killed
0,Afghanistan,AFG,1970,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Afghanistan,AFG,1971,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Afghanistan,AFG,1972,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Afghanistan,AFG,1973,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Afghanistan,AFG,1974,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [3]:
# determining the shape of the data

print(f'Rows: {df.shape[0]}')
print(f'Columns: {df.shape[1]}')

Rows: 10517
Columns: 21

In [4]:
# Determining the columns in the dataframe
df.columns.tolist()

['Entity',
 'Code',
 'Year',
 'Terrorist attacks',
 'Terrorism deaths',
 'Attack method: Hijacking',
 'Attack method: Hostage Taking (Barricade Incident)',
 'Attack method: Unarmed Assault',
 'Attack method: Facility/Infrastructure Attack',
 'Attack method: Hostage Taking (Kidnapping)',
 'Attack method: Assassination',
 'Attack method: Armed Assault',
 'Attack method: Bombing/Explosion',
 'Death Age 100+',
 'Death Age: 51-99 ',
 'Death Age : 21-50 ',
 'Death Age : 11-20 ',
 'Death Age : 6-10 ',
 'Death Age :  1-5',
 'Terrorist Death Type : Suicide',
 'Terrorist Death Type : Killed']

In [5]:
# Determining if there are entries for the philippines

len(df[df['Entity'] == 'Philippines']) # will get the count of the row na philippines yung entity

51

In [6]:
df[df['Entity'] == 'Philippines']

,Entity,Code,Year,Terrorist attacks,Terrorism deaths,Attack method: Hijacking,Attack method: Hostage Taking (Barricade Incident),Attack method: Unarmed Assault,Attack method: Facility/Infrastructure Attack,Attack method: Hostage Taking (Kidnapping),Attack method: Assassination,Attack method: Armed Assault,Attack method: Bombing/Explosion,Death Age 100+,Death Age: 51-99,Death Age : 21-50,Death Age : 11-20,Death Age : 6-10,Death Age : 1-5,Terrorist Death Type : Suicide,Terrorist Death Type : Killed
7240,Philippines,PHL,1970,10,41,0,0,0,0,0,1,0,6,0,0,1,0,0,4,0,41
7241,Philippines,PHL,1971,4,0,1,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0
7242,Philippines,PHL,1972,7,2,0,0,0,0,0,0,5,2,0,0,0,0,0,2,0,2
7243,Philippines,PHL,1973,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7244,Philippines,PHL,1974,1,3,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,3
7245,Philippines,PHL,1975,4,1,0,0,0,0,3,0,0,1,0,0,0,0,0,1,0,1
7246,Philippines,PHL,1976,10,47,2,0,0,1,2,0,4,1,0,0,0,2,2,1,0,47
7247,Philippines,PHL,1977,2,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0
7248,Philippines,PHL,1978,36,128,0,0,0,0,3,1,13,16,0,0,1,1,4,14,0,128
7249,Philippines,PHL,1979,50,107,0,1,0,2,6,17,12,3,0,0,0,2,5,24,0,107
7250,Philippines,PHL,1980,60,163,0,0,0,6,2,1,5,44,0,0,1,4,8,10,0,163
7251,Philippines,PHL,1981,31,176,0,2,0,4,3,1,5,7,0,0,0,8,3,9,0,176
7252,Philippines,PHL,1982,38,139,0,0,0,4,1,8,7,12,0,0,1,4,4,17,0,139
7253,Philippines,PHL,1983,16,101,0,0,0,0,0,3,4,7,0,0,1,2,1,7,0,101
7254,Philippines,PHL,1984,43,262,0,0,0,0,2,17,3,3,0,1,1,3,7,28,0,262
7255,Philippines,PHL,1985,124,452,0,2,0,6,4,31,10,21,0,0,7,9,6,46,0,452
7256,Philippines,PHL,1986,80,322,1,0,0,1,9,24,13,16,0,0,1,9,9,36,0,322
7257,Philippines,PHL,1987,160,404,0,4,1,3,7,36,39,61,0,0,3,7,12,65,0,404
7258,Philippines,PHL,1988,210,550,0,2,0,5,15,82,74,29,0,0,2,12,14,126,0,550
7259,Philippines,PHL,1989,156,393,0,1,0,3,7,59,46,40,0,0,2,7,12,80,0,393
7260,Philippines,PHL,1990,320,457,1,1,0,8,13,67,90,140,0,0,1,5,17,108,0,457
7261,Philippines,PHL,1991,162,432,0,1,0,4,14,23,61,59,0,0,4,5,19,53,0,432
7262,Philippines,PHL,1992,162,395,0,0,0,2,13,45,40,62,0,0,3,1,9,83,0,395
7263,Philippines,PHL,1994,72,126,0,0,0,0,34,9,9,19,0,0,0,3,4,26,0,126
7264,Philippines,PHL,1995,63,201,0,1,0,1,20,11,13,13,1,0,0,1,4,26,0,201
7265,Philippines,PHL,1996,61,95,0,1,0,2,14,8,15,13,0,0,0,0,4,26,0,95
7266,Philippines,PHL,1997,57,98,0,0,0,0,19,3,16,15,0,0,0,0,4,29,0,98
7267,Philippines,PHL,1998,18,6,0,0,0,1,5,0,2,10,0,0,0,0,0,4,0,6
7268,Philippines,PHL,1999,31,45,0,0,1,0,9,1,8,12,0,0,0,1,2,7,0,45
7269,Philippines,PHL,2000,132,290,0,0,0,3,14,4,36,73,0,0,2,3,7,52,6,284
7270,Philippines,PHL,2001,50,154,0,1,0,0,8,9,15,17,0,1,0,3,2,20,0,154
7271,Philippines,PHL,2002,48,125,0,0,0,4,6,7,14,16,0,0,0,4,3,23,0,125
7272,Philippines,PHL,2003,107,288,1,0,0,9,3,6,34,49,0,0,1,6,10,39,25,263
7273,Philippines,PHL,2004,31,203,0,0,0,0,2,4,13,12,1,0,1,1,2,14,0,203
7274,Philippines,PHL,2005,25,49,0,0,0,1,0,3,9,10,0,0,0,1,1,13,0,49
7275,Philippines,PHL,2006,58,60,0,0,0,3,9,8,12,25,0,0,0,0,3,23,0,60
7276,Philippines,PHL,2007,65,115,0,0,0,2,7,4,20,31,0,0,0,1,7,29,0,115
7277,Philippines,PHL,2008,276,220,0,0,0,34,32,12,76,107,0,0,1,2,1,93,1,219
7278,Philippines,PHL,2009,229,151,2,1,0,26,16,13,63,100,0,0,0,1,2,82,0,151
7279,Philippines,PHL,2010,204,155,1,1,0,29,13,10,90,56,0,0,0,1,2,90,2,153
7280,Philippines,PHL,2011,151,127,1,0,0,22,13,11,45,53,0,0,0,0,3,63,0,127
7281,Philippines,PHL,2012,249,212,1,1,0,14,13,22,83,111,0,0,0,3,3,100,0,212
7282,Philippines,PHL,2013,651,432,1,3,1,52,60,109,231,181,0,0,0,0,14,238,1,431
7283,Philippines,PHL,2014,597,472,1,1,0,46,55,67,243,162,0,0,2,1,9,216,0,472
7284,Philippines,PHL,2015,721,447,2,6,0,44,52,105,269,227,0,0,0,0,4,292,0,447
7285,Philippines,PHL,2016,632,415,9,9,0,28,41,151,186,200,0,0,1,1,4,263,0,415
7286,Philippines,PHL,2017,695,500,11,15,1,82,57,106,217,168,0,0,0,0,11,280,1,499
7287,Philippines,PHL,2018,601,440,2,5,0,40,29,146,217,144,0,0,0,1,4,290,12,428
7288,Philippines,PHL,2019,467,399,0,4,0,29,20,148,160,92,0,0,0,3,5,254,37,362
7289,Philippines,PHL,2020,294,280,0,2,0,15,10,75,122,62,0,0,0,1,5,166,16,264
7290,Philippines,PHL,2021,104,100,1,1,0,7,5,36,30,23,0,0,0,0,1,65,0,100

In [7]:
# getting the sum of the metrics for the philippines

numerical_columns = ['Terrorist attacks',
 'Terrorism deaths',
 'Attack method: Hijacking',
 'Attack method: Hostage Taking (Barricade Incident)',
 'Attack method: Unarmed Assault',
 'Attack method: Facility/Infrastructure Attack',
 'Attack method: Hostage Taking (Kidnapping)',
 'Attack method: Assassination',
 'Attack method: Armed Assault',
 'Attack method: Bombing/Explosion',
 'Death Age 100+',
 'Death Age: 51-99 ',
 'Death Age : 21-50 ',
 'Death Age : 11-20 ',
 'Death Age : 6-10 ',
 'Death Age :  1-5',]

df.loc[df['Code'] == 'PHL', numerical_columns].sum()

Terrorist attacks                                      8375
Terrorism deaths                                      10780
Attack method: Hijacking                                 38
Attack method: Hostage Taking (Barricade Incident)       66
Attack method: Unarmed Assault                            4
Attack method: Facility/Infrastructure Attack           543
Attack method: Hostage Taking (Kidnapping)              670
Attack method: Assassination                           1505
Attack method: Armed Assault                           2681
Attack method: Bombing/Explosion                       2534
Death Age 100+                                            2
Death Age: 51-99                                          2
Death Age : 21-50                                        37
Death Age : 11-20                                       119
Death Age : 6-10                                        253
Death Age :  1-5                                       3538
dtype: int64

In [8]:
# getting the total number of attacks and the breakdown

attack_metrics = ['Terrorist attacks','Attack method: Hijacking',
 'Attack method: Hostage Taking (Barricade Incident)',
 'Attack method: Unarmed Assault',
 'Attack method: Facility/Infrastructure Attack',
 'Attack method: Hostage Taking (Kidnapping)',
 'Attack method: Assassination',
 'Attack method: Armed Assault',
 'Attack method: Bombing/Explosion']

df.loc[df['Code'] == 'PHL', attack_metrics].sum()

Terrorist attacks                                     8375
Attack method: Hijacking                                38
Attack method: Hostage Taking (Barricade Incident)      66
Attack method: Unarmed Assault                           4
Attack method: Facility/Infrastructure Attack          543
Attack method: Hostage Taking (Kidnapping)             670
Attack method: Assassination                          1505
Attack method: Armed Assault                          2681
Attack method: Bombing/Explosion                      2534
dtype: int64

In [9]:
# getting the total casualties and the breakdown

death_metrics = ['Terrorism deaths', 'Death Age 100+',
 'Death Age: 51-99 ',
 'Death Age : 21-50 ',
 'Death Age : 11-20 ',
 'Death Age : 6-10 ',
 'Death Age :  1-5',
 'Terrorist Death Type : Suicide',
 'Terrorist Death Type : Killed' ]

df.loc[df['Code'] == 'PHL', death_metrics].sum()

Terrorism deaths                  10780
Death Age 100+                        2
Death Age: 51-99                      2
Death Age : 21-50                    37
Death Age : 11-20                   119
Death Age : 6-10                    253
Death Age :  1-5                   3538
Terrorist Death Type : Suicide      101
Terrorist Death Type : Killed     10679
dtype: int64