In [1]:
import pandas as pd

In [3]:
# creating the dataframe 

df = pd.read_csv('terrorist-attacks.csv')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

df.head()

,Entity,Code,Year,Terrorist attacks,Terrorism deaths,Attack method: Hijacking,Attack method: Hostage Taking (Barricade Incident),Attack method: Unarmed Assault,Attack method: Facility/Infrastructure Attack,Attack method: Hostage Taking (Kidnapping),Attack method: Assassination,Attack method: Armed Assault,Attack method: Bombing/Explosion,Death Age 100+,Death Age: 51-99,Death Age : 21-50,Death Age : 11-20,Death Age : 6-10,Death Age : 1-5,Terrorist Death Type : Suicide,Terrorist Death Type : Killed
0,Afghanistan,AFG,1970,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Afghanistan,AFG,1971,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Afghanistan,AFG,1972,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Afghanistan,AFG,1973,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Afghanistan,AFG,1974,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0